"""test

Revision ID: 81eb01d4960d
Revises: 47846d682363
Create Date: 2024-06-12 14:03:42.396467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81eb01d4960d'
down_revision = '47846d682363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routinetemplates', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routinetemplates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
