"""test

Revision ID: e7997b1b21a5
Revises: 
Create Date: 2024-06-12 11:42:12.195555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7997b1b21a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routinetemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_timer_length', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routinetemplates_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasktemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('task_note', sa.String(), nullable=True),
    sa.Column('timer_length', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasktemplates_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskroutine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasktemplate_id', sa.String(), nullable=True),
    sa.Column('routinetemplate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routinetemplate_id'], ['routinetemplates.id'], name=op.f('fk_taskroutine_routinetemplate_id_routinetemplates')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskroutine')
    op.drop_table('tasktemplates')
    op.drop_table('routinetemplates')
    op.drop_table('users')
    # ### end Alembic commands ###
